apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      name: bookstore
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: public.ecr.aws/n4e0r7f3/onlinebook:${env.BUILD_ID}
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: bookstore
spec:
  type: NodePort
  selector:
    app: bookstore
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31257
